troubleshooted github workflow

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -38,7 +38,8 @@ jobs:
     - name: Extract version
       id: extract_version
       run: |
-        echo "::set-output name=version::$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])")"
+        version=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])") || echo "Failed to extract version"
+        echo "::set-output name=version::$version"
 
     - name: Check if version is updated
       id: check_version
